feat: farm upgrades
mxz7/nypsi pull request #1681
Opened 2024-12-09 16:05 UTC by GrowlingGrizzly

Some things that need to be done:

* emojis
* balancing
* more ideas? maybe

2024-12-09 16:25 UTC, mxz7 requested changes
ok for balancing the sticks are gonna have to be suuuper rare.

and i think for the item thing it needs to be a lot. otherwise it's gonna be super easy to get

maybe silo should be a 10-15% upgrade too, since that will still be A LOT if you have a lot of plants. and probably about maybe 70 steel? not sure

2024-12-09 16:25 UTC, mxz7 commented on src/utils/functions/economy/farm.ts
> +    const userUpgrades = await getFarmUpgrades(id);
put it outside the loop so it doesn't fetch upgrades on every plant

2024-12-09 16:25 UTC, mxz7 commented on package.json
> +    "twemoji-parser": "^14.0.0"
this is bad package

2024-12-09 17:21 UTC, GrowlingGrizzly commented
heres images for stick and hoes, idk what we want for a silo emoji

![image](https://github.com/user-attachments/assets/c07c06df-ff21-475d-82d0-0e4ebb6ab2cf)
![image](https://github.com/user-attachments/assets/201fdfc6-8139-448c-858e-d2722475843b)
![image](https://github.com/user-attachments/assets/9598c6a1-74e4-49bc-876c-9331e875de94)
![image](https://github.com/user-attachments/assets/4d254bc4-ac82-49e1-8a6f-d0bbeed9082f)
![image](https://github.com/user-attachments/assets/6eceab69-d84d-41d3-8100-8c6f2df3a4e1)
![image](https://github.com/user-attachments/assets/866f4d9a-eb8d-45ea-be46-35ab1ef65ba2)

2024-12-11 19:34 UTC, mxz7 approved these changes

2024-12-11 20:52 UTC, merged